services:
  postgres:
    image: postgres:15-alpine
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init_scripts:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  airflow:
    build: .
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW__CORE__FERNET_KEY}
      AIRFLOW__CORE__TEST_CONNECTION: Enabled
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER_AIRFLOW}:${POSTGRES_PASSWORD_AIRFLOW}@postgres:5432/${POSTGRES_DATABASE_AIRFLOW}
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_DB_MIGRATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-airflow}
      _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-airflow}
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    command: standalone
    volumes:
      - ./dags:/opt/airflow/dags
    restart: always

  superset:
    image: apache/superset:latest
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SUPERSET_SECRET_KEY: ${SUPERSET_SECRET_KEY}
      SUPERSET_ENV: development
      DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER_SUPERSET}:${POSTGRES_PASSWORD_SUPERSET}@postgres:5432/${POSTGRES_DATABASE_SUPERSET}
    ports:
      - "8088:8088"
    command: >
      /bin/sh -c "
      pip install psycopg2-binary &&
      superset fab create-admin --username admin --firstname Admin --lastname User --email admin@superset.com --password admin &&
      superset db upgrade &&
      superset init &&
      superset run -h 0.0.0.0 -p 8088
      "
    restart: always


volumes:
  postgres-data:
